liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        squared_thumbnail_small:
            filters:
                thumbnail:
                    size:   [200, 200]
                    mode:   outbound
                    allow_upscale: true