# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.2-apache-stretch-node-browsers
        environment:
            APP_ENV: dev
            DATABASE_URL: mysql://root:root@localhost/webmd
      - image: circleci/mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: webmd

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19

    steps:
      - checkout

      - run: sudo apt-get update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo apt-get install imagemagick
      - run: sudo docker-php-ext-install pdo_mysql
      - run: sudo add-apt-repository -y ppa:ondrej/php
      - run: sudo apt-get install php-imagick
      - run:
            name:   Wait for MYSQL
            command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

      - run: sudo composer self-update
      - run: composer install -n --prefer-dist

      # prepare the database
      - run: php bin/console doctrine:migrations:migrate --env=test --no-interaaction
